echo -e "\E[H\E[J"
echo -e "\E(0"
echo -e "\E[10;5Hlqqqqqqk"
echo -e "\E[11;5Hxaaaaaax"
echo -e "\E[12;5Hx    aax"
echo -e "\E[13;5Hx   aa x"
echo -e "\E[14;5Hx  aa  x"
echo -e "\E[15;5Hx  aa  x"
echo -e "\E[16;5Hx  aa  x"
echo -e "\E[17;5Hmqqqqqqj"
echo -e "\E(B"
